#!/bin/bash
for i in $(seq 0 9)
do
  for j in $(seq 0 9)
  do
    if [ "$i" -lt "$j" ]
    then
      printf "%d%d" "$i" "$j"
      if [ "$i" -ne 8 ] || [ "$j" -ne 9 ]
      then
        printf ", "
      fi
    fi
  done
done
printf "\n"
